# Generated by Django 4.2.7 on 2023-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_e", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=300)),
                ("position", models.CharField(max_length=200)),
                ("start_year", models.IntegerField(max_length=1000)),
                ("total_attend", models.IntegerField(max_length=1000)),
            ],
        ),
    ]
